[workspace]
resolver = "2"
members = [
    "rail_town",
    "rail_sim",
    "rail_map",
    "rail_net",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
bevy = { version = "0.18", default-features = false }
bevy_app = "0.18"
bevy_ecs = "0.18"
rand = { version = "0.8", default-features = false, features = ["std_rng"] }
serde = { version = "1", features = ["derive"] }
